printWidth: 80 # 打印宽度
tabWidth: 2 # tab宽度
useTabs: false # 使用tab缩进
semi: true # 使用分号
singleQuote: true # 使用单引号
quoteProps: as-needed # 属性引号类型
jsxSingleQuote: false # jsx单引号
trailingComma: all # 末尾逗号
bracketSpacing: true # 大括号空格
bracketSameLine: false # 大括号换行
arrowParens: always # 箭头函数括号
requirePragma: false # 需要编译指示
insertPragma: false # 插入编译指示
proseWrap: preserve # 文本换行
htmlWhitespaceSensitivity: ignore # html空格敏感度, ignore: 空格不敏感
vueIndentScriptAndStyle: true # vue缩进
endOfLine: lf # 换行符类型
embeddedLanguageFormatting: auto # 嵌入语言格式化
singleAttributePerLine: true # 单个属性换行
